- hosts: all
  sudo: yes
  tasks:
    - apt: name={{ item }} state=present update_cache=true
      with_items: 
        - git
        - tmux
        - vim
        - openjdk-8-jdk

    - get_url: 
          url=http://mirrors.dcarsat.com.ar/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
          dest=/root/apache-maven-3.3.3-bin.tar.gz mode=0440

    - shell: src=/root/apache-maven-3.3.3-bin.tar.gz dest=/usr/bin/ copy=no
